export * from './home';
export * from './link';
export * from './contact';
export * from './Bar';
export * from './footer';
export * from './navbar';
export * from './services/ourServices/card';
export * from './Bar'
export * from './catalogue'
export * from './common'
export * from './cards';
