name: Deploy S3 - DEV

on:
  pull_request:
    branches:
      - release/*

env:
  REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: ${{ secrets.S3_BUCKET}}

jobs:
  git-event:
    name: Print git environment
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Printenv
        run: printenv

  publish-spa:
    name: publish site
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: Clear all files in S3 Bucket
        uses: aws s3 rm ${{ env.S3_BUCKET }} --recursive
      - name: Upload public to S3 Bucket
        uses: aws s3 cp public ${{ env.S3_BUCKET }} --recursive
