#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

cyan='\e[1;36m'
resetColor='\e[0m'

printf "\n$cyan-------- Checking Commit Message ---------$resetColor\n\n"
npx --no -- commitlint --edit ${1}



