#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

green='\e[1;32m'
cyan='\e[1;36m'
purple='\e[1;35m'
resetColor='\e[0m'

printf "\n$purple-------- Start Run format Pre Staged---------$resetColor\n\n"
# npm run staged
echo ""
