name: Deploy FTP - PROD

on:
  push:
    branches:
      - feature/updateHome

env:
  FTP_ACCESS_SERVER_NAME: ${{secrets.FTP_SERVER}}
  FTP_ACCESS_USER: ${{secrets.FTP_USER}}
  FTP_ACCESS_PASSWORD: ${{secrets.FTP_PASSWORD}}
  NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
  NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

jobs:
  git-event:
    name: Print git environment
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Printenv
        run: printenv

  publish:
    name: publish site
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: registry npm add file
        run: printf "registry=https://${{ env.NPM_REGISTRY }}\n//${{ env.NPM_REGISTRY }}:_authToken=${{ env.NPM_REGISTRY_TOKEN }}\nalways-auth=true" >> ~/.npmrc | cat ~/.npmrc
      - name: yarn install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Deploy Action FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{env.FTP_ACCESS_SERVER_NAME}}
          username: ${{env.FTP_ACCESS_USER}}
          password: ${{env.FTP_ACCESS_PASSWORD}}
          local-dir: ./public/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.idea/**
            **/.vscode/**
            **/.github/**
            **/.cache/**
            **/.husky/**
            **/src/**
            **/static/**
            **/sistema/**
            **/back/**
            **/demo/**
            **/front/**
            .gitignore
            README.md
