name: Deploy FTP

on:
  pull_request:
    branches:
      - release/*

env:
  FTP_SERVER: 94.130.64.174
  FTP_USERNAME: dathaplus@tribologyec.com
  FTP_PASSWORD: 8vYDhjzjnpMCEMjdSPkK
  NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
  NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

jobs:

  publish:
    name: publish site
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: registry npm add file
        run: printf "registry=https://${{ env.NPM_REGISTRY }}\n//${{ env.NPM_REGISTRY }}:_authToken=${{ env.NPM_REGISTRY_TOKEN }}\nalways-auth=true" >> ~/.npmrc | cat ~/.npmrc
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: create files to transfer
        run: tar czvf build.tar.gz _next package.json
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ env.FTP_SERVER }}
          user: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          local_dir: "./build.tar.gz"
          remote_dir: "/domains/tribologyec.com/public_html"